### ISSUE TITLE
Cannot serialize property without type

### ISSUE THREAD

**Issue by joelhegg** [edcarroll/ta-json#20]
When I try the quickstart using Typescript 2.6.1 I get this error:
```
    Cannot serialize property 'firstName' without type!

      at node_modules/ta-json/src/methods/serialize.ts:30:23
          at Map.forEach (<anonymous>)
      at node_modules/ta-json/src/methods/serialize.ts:28:22
          at Array.forEach (<anonymous>)
      at serializeRootObject (node_modules/ta-json/src/methods/serialize.ts:27:17)
      at Object.serialize (node_modules/ta-json/src/methods/serialize.ts:11:12)
      at Function.Object.<anonymous>.JSON.serialize (node_modules/ta-json/src/json.ts:15:16)
      at Function.Object.<anonymous>.JSON.stringify (node_modules/ta-json/src/json.ts:19:43)
```

I can make the error go away by adding `@JsonElementType(String)` below each of the `@JsonProperty()` decorators. I don't think this should be necessary though. Is this a bug or some bit of configuration I'm missing?

**Comment by joelhegg** [comment]
Answering my own question, http://www.typescriptlang.org/docs/handbook/decorators.html has the answer. These two config options are required for this code to work:

```
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
```
